import asyncio
import math
import tempfile
import uuid
from pathlib import Path
from typing import Dict, List

from PIL import Image, ImageDraw, ImageFont


class VoiceRenderer:
    """渲染插件帮助图和语音索引图。"""

    COLOR_BG = (26, 26, 26)
    COLOR_CONTAINER = (37, 37, 37)
    COLOR_CARD = (48, 48, 48)
    COLOR_SKIN_CARD = (58, 56, 48)
    COLOR_ACCENT = (255, 205, 0)
    COLOR_TEXT_MAIN = (255, 255, 255)
    COLOR_TEXT_SUB = (200, 200, 200)
    COLOR_BORDER = (68, 68, 68)

    def __init__(self, font_path: str = None, output_dir: str = None):
        self.font_path = font_path
        self._font_cache = {}
        self.output_dir = Path(
            output_dir or Path(tempfile.gettempdir()) / "astrbot_plugin_mrfz"
        )
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _load_font(self, size: int):
        if size in self._font_cache:
            return self._font_cache[size]

        font = None
        candidates = []
        if self.font_path:
            candidates.append(Path(self.font_path))
        candidates.extend(
            [
                Path(__file__).parent / "SourceHanSerifCN-Medium-6.otf",
                Path("msyh.ttc"),
            ]
        )

        for candidate in candidates:
            try:
                if candidate.exists() or candidate.name == "msyh.ttc":
                    font = ImageFont.truetype(str(candidate), size)
                    break
            except (OSError, IOError):
                continue

        if font is None:
            font = ImageFont.load_default()

        self._font_cache[size] = font
        return font

    def _new_output_path(self, prefix: str) -> Path:
        return self.output_dir / f"{prefix}_{uuid.uuid4().hex}.png"

    @staticmethod
    def _save_atomic(image: Image.Image, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        temp_path = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")

        try:
            image.save(temp_path, format="PNG")
            temp_path.replace(path)
        finally:
            temp_path.unlink(missing_ok=True)

    def _draw_footer(
        self,
        draw: ImageDraw.ImageDraw,
        width: int,
        height: int,
    ):
        text = "GENERATED BY astrbot_plugin_mrfz | by bushikq"
        font = self._load_font(16)
        bbox = draw.textbbox((0, 0), text, font=font)
        text_width = bbox[2] - bbox[0]

        draw.line(
            [(30, height - 40), (width - 30, height - 40)],
            fill=self.COLOR_BORDER,
            width=1,
        )
        draw.text(
            (width - text_width - 30, height - 30),
            text,
            font=font,
            fill=(100, 100, 100),
        )

    async def render_help(self) -> str:
        """在线程中渲染帮助图片，避免阻塞事件循环。"""
        return await asyncio.to_thread(self._render_help_logic)

    def _render_help_logic(self) -> str:
        width, height = 900, 680
        image = Image.new("RGB", (width, height), self.COLOR_BG)
        draw = ImageDraw.Draw(image)

        draw.rectangle(
            [(20, 20), (width - 20, height - 20)],
            fill=self.COLOR_CONTAINER,
        )
        draw.rectangle(
            [(20, 20), (25, height - 20)],
            fill=self.COLOR_ACCENT,
        )
        draw.text(
            (50, 40),
            "VOICE DATABASE",
            font=self._load_font(32),
            fill=self.COLOR_TEXT_MAIN,
        )
        draw.text(
            (340, 50),
            "PLUGIN HELP",
            font=self._load_font(20),
            fill=self.COLOR_ACCENT,
        )
        draw.line(
            [(50, 85), (width - 50, 85)],
            fill=self.COLOR_ACCENT,
            width=2,
        )

        commands = [
            (
                "/mrfz [角色] [语音(可省略)] [语言(可省略)]",
                "查询并播放语音 语言:中文/方言/日语/英语/韩语/意语",
                "例: /mrfz 凯尔希 问候",
            ),
            (
                "/mrfz_list",
                "查看已下载干员/皮肤索引",
                "例: /mrfz_list",
            ),
            (
                "/mrfz_fetch [角色名]",
                "从 PRTS Wiki 下载数据",
                "例: /mrfz_fetch 陈",
            ),
            (
                "/mrfz_bind [触发] [角色] [语音] [语言(可省略)]",
                "绑定快捷指令",
                "例: /mrfz_bind 早安 阿米娅 问候 中文",
            ),
            (
                "/mrfz_unbind [触发词]",
                "解绑快捷指令",
                "例: /mrfz_unbind 早安",
            ),
        ]

        y = 110
        command_font = self._load_font(22)
        desc_font = self._load_font(20)

        for command, description, example in commands:
            draw.rectangle(
                [(50, y), (width - 50, y + 80)],
                fill=self.COLOR_CARD,
                outline=self.COLOR_BORDER,
            )
            draw.text(
                (65, y + 10),
                command,
                font=command_font,
                fill=self.COLOR_ACCENT,
            )
            draw.text(
                (65, y + 45),
                description,
                font=desc_font,
                fill=self.COLOR_TEXT_MAIN,
            )

            example_width = draw.textlength(example, font=desc_font)
            draw.text(
                (width - 65 - example_width, y + 45),
                example,
                font=desc_font,
                fill=(150, 150, 150),
            )
            y += 95

        self._draw_footer(draw, width, height)

        save_path = self._new_output_path("help")
        self._save_atomic(image, save_path)
        return str(save_path.absolute())

    def render_image(
        self,
        data: Dict,
        voice_descriptions: List[str],
    ) -> str:
        """渲染详细列表图片。"""
        custom_commands = data.get("custom_commands", [])
        operators = data.get("operators", [])
        skin_operators = data.get("skin_operators", [])

        col_count = 3
        padding = 30
        card_height = 80
        card_width = 280
        gap = 15

        def section_height(items):
            if not items:
                return 0

            rows = math.ceil(len(items) / col_count)
            return 70 + rows * (card_height + gap)

        desc_col_count = 6
        desc_rows = math.ceil(len(voice_descriptions) / desc_col_count)

        sections_height = sum(
            section_height(items)
            for items in (
                custom_commands,
                operators,
                skin_operators,
            )
        )

        total_height = 250 + sections_height + desc_rows * 30
        canvas_width = max(
            960,
            padding * 2 + col_count * (card_width + gap),
        )

        image = Image.new(
            "RGB",
            (canvas_width, total_height),
            self.COLOR_BG,
        )
        draw = ImageDraw.Draw(image)

        draw.rectangle(
            [
                (20, 20),
                (canvas_width - 20, total_height - 20),
            ],
            fill=self.COLOR_CONTAINER,
        )
        draw.rectangle(
            [
                (20, 20),
                (25, total_height - 20),
            ],
            fill=self.COLOR_ACCENT,
        )

        title_font = self._load_font(32)
        sub_font = self._load_font(18)
        section_font = self._load_font(20)
        name_font = self._load_font(20)
        tag_font = self._load_font(14)

        draw.text(
            (50, 40),
            "VOICE DATABASE",
            font=title_font,
            fill=self.COLOR_TEXT_MAIN,
        )
        draw.text(
            (340, 52),
            "PRTS TERMINAL",
            font=sub_font,
            fill=self.COLOR_ACCENT,
        )
        draw.line(
            [(50, 85), (canvas_width - 50, 85)],
            fill=self.COLOR_ACCENT,
            width=2,
        )

        current_y = 110

        def draw_section(
            title,
            items,
            start_y,
            *,
            is_skin=False,
            is_custom=False,
        ):
            if not items:
                return start_y

            draw.rectangle(
                [
                    (50, start_y),
                    (canvas_width - 50, start_y + 35),
                ],
                fill=(51, 51, 51),
            )
            draw.rectangle(
                [
                    (50, start_y),
                    (53, start_y + 35),
                ],
                fill=self.COLOR_ACCENT,
            )
            draw.text(
                (65, start_y + 5),
                title,
                font=section_font,
                fill=self.COLOR_TEXT_MAIN,
            )

            grid_y = start_y + 50

            for index, item in enumerate(items):
                row, col = divmod(index, col_count)

                x = 50 + col * (card_width + gap)
                y = grid_y + row * (card_height + gap)

                background = self.COLOR_SKIN_CARD if is_skin else self.COLOR_CARD

                draw.rectangle(
                    [
                        (x, y),
                        (x + card_width, y + card_height),
                    ],
                    fill=background,
                    outline=self.COLOR_BORDER,
                )

                avatar_path = item.get("avatar_path")

                if avatar_path and Path(avatar_path).is_file():
                    try:
                        with Image.open(avatar_path) as avatar:
                            avatar = avatar.convert("RGB").resize((60, 60))
                            image.paste(
                                avatar,
                                (x + 10, y + 10),
                            )
                    except (OSError, IOError, ValueError):
                        draw.rectangle(
                            [
                                (x + 10, y + 10),
                                (x + 70, y + 70),
                            ],
                            fill=(20, 20, 20),
                        )
                else:
                    draw.rectangle(
                        [
                            (x + 10, y + 10),
                            (x + 70, y + 70),
                        ],
                        fill=(20, 20, 20),
                    )

                text_x = x + 80

                if is_custom:
                    trigger = str(item.get("trigger", ""))
                    target = str(item.get("target", ""))
                    lang_display = str(item.get("lang_display", ""))

                    tag_width = (
                        draw.textlength(
                            trigger,
                            font=tag_font,
                        )
                        + 10
                    )

                    draw.rectangle(
                        [
                            (text_x, y + 12),
                            (
                                text_x + tag_width,
                                y + 32,
                            ),
                        ],
                        fill=self.COLOR_ACCENT,
                    )
                    draw.text(
                        (text_x + 5, y + 12),
                        trigger,
                        font=tag_font,
                        fill=(0, 0, 0),
                    )

                    if lang_display:
                        draw.text(
                            (
                                text_x + tag_width + 5,
                                y + 12,
                            ),
                            f"[{lang_display}]",
                            font=tag_font,
                            fill=(150, 150, 150),
                        )

                    draw.text(
                        (text_x, y + 40),
                        f"-> {target}"[:16],
                        font=tag_font,
                        fill=self.COLOR_TEXT_SUB,
                    )
                else:
                    name = str(item.get("name", ""))
                    color = self.COLOR_ACCENT if is_skin else self.COLOR_TEXT_MAIN

                    draw.text(
                        (text_x, y + 10),
                        name,
                        font=name_font,
                        fill=color,
                    )

                    tag_x = text_x

                    for language in item.get(
                        "languages",
                        [],
                    ):
                        display = str(
                            language.get(
                                "display",
                                "CN",
                            )
                        )
                        color_rgb = language.get(
                            "color",
                            (100, 100, 100),
                        )

                        draw.rectangle(
                            [
                                (tag_x, y + 40),
                                (tag_x + 24, y + 58),
                            ],
                            fill=(68, 68, 68),
                        )
                        draw.rectangle(
                            [
                                (tag_x, y + 56),
                                (tag_x + 24, y + 58),
                            ],
                            fill=color_rgb,
                        )
                        draw.text(
                            (tag_x + 4, y + 40),
                            display[:1],
                            font=tag_font,
                            fill=(200, 200, 200),
                        )
                        tag_x += 28

            rows = math.ceil(len(items) / col_count)
            return grid_y + rows * (card_height + gap) + 20

        current_y = draw_section(
            "自定义快捷指令 // CUSTOM SHORTCUTS",
            custom_commands,
            current_y,
            is_custom=True,
        )
        current_y = draw_section(
            "已登记干员 // REGISTERED OPERATORS",
            operators,
            current_y,
        )
        current_y = draw_section(
            "时装记录 // OUTFIT RECORDS",
            skin_operators,
            current_y,
            is_skin=True,
        )

        draw.rectangle(
            [
                (50, current_y),
                (canvas_width - 50, current_y + 35),
            ],
            fill=(51, 51, 51),
        )
        draw.rectangle(
            [
                (50, current_y),
                (53, current_y + 35),
            ],
            fill=self.COLOR_ACCENT,
        )
        draw.text(
            (65, current_y + 5),
            "系统支持的语音类型 // SYSTEM MODULES",
            font=section_font,
            fill=self.COLOR_TEXT_MAIN,
        )

        current_y += 50
        desc_width = (canvas_width - 100) / desc_col_count

        for index, text in enumerate(voice_descriptions):
            row, col = divmod(
                index,
                desc_col_count,
            )
            x = 50 + col * desc_width
            y = current_y + row * 30

            draw.ellipse(
                [
                    (x, y + 8),
                    (x + 4, y + 12),
                ],
                fill=self.COLOR_ACCENT,
            )
            draw.text(
                (x + 10, y),
                text,
                font=tag_font,
                fill=self.COLOR_TEXT_SUB,
            )

        self._draw_footer(
            draw,
            canvas_width,
            total_height,
        )

        output_path = self._new_output_path("list")
        self._save_atomic(
            image,
            output_path,
        )
        return str(output_path.absolute())
